# Generated by Django 3.1.7 on 2022-08-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220807_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_berkas',
            options={'verbose_name_plural': 'Detail Berkas'},
        ),
        migrations.RemoveField(
            model_name='detail_berkas',
            name='item',
        ),
        migrations.AddField(
            model_name='detail_berkas',
            name='judul_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.judul_item'),
        ),
    ]
