# Generated by Django 3.1.7 on 2022-08-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20220808_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_berkas',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='detail_berkas',
            name='guru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.guru'),
        ),
        migrations.AddField(
            model_name='detail_berkas',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.kelas'),
        ),
        migrations.AddField(
            model_name='detail_berkas',
            name='mata_pelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.mata_pelajaran'),
        ),
    ]
