# Generated by Django 3.1.7 on 2022-08-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20220808_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_berkas',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.guru'),
        ),
        migrations.AlterField(
            model_name='detail_berkas',
            name='judul_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.judul_item'),
        ),
        migrations.AlterField(
            model_name='detail_berkas',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.kelas'),
        ),
        migrations.AlterField(
            model_name='detail_berkas',
            name='mata_pelajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.mata_pelajaran'),
        ),
    ]
