# Generated by Django 4.1 on 2022-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20220808_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='standar',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='arsip/data_qrcode'),
        ),
    ]
